export const FETCH_TICKET_LIST ="FETCH_TICKET_LIST";
export const SAVE_BUISNESSDETAILS = "SAVE_BUISNESSDETAILS";
export const FETCH_BANKDETAILS = "FETCH_BANKDETAILS";
export const CREATE_STATUS = "CREATE_STATUS";
export const FETCH_AGREEMENT = "FETCH_AGREEMENT";
export const FETCH_AGREEMENTSTATUS = "FETCH_AGREEMENTSTATUS";