export const GET_ALL_MY_ORDERS = "GET_ALL_MY_ORDERS";
export const ORDER_DETAILS = "ORDER_DETAILS";
export const TRACK_ORDER_STATUS = "TRACK_ORDER_STATUS";
export const ORDER_CANCELLATION = "ORDER_CANCELLATION";
export const GIVE_REVIEW = "GIVE_REVIEW";