export const FETCH_CART = 'FETCH_CART';
export const ADDTO_CART = 'ADDTO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const AFTER_MOVETOWISHLIST_FETCH = 'AFTER_MOVETOWISHLIST_FETCH';
export const API_CALLING = 'API_CALLING'

