export const FETCH_BUISNESSDETAILS ="FETCH_BUISNESSDETAILS";
export const SAVE_BUISNESSDETAILS = "SAVE_BUISNESSDETAILS";
export const FETCH_BANKDETAILS = "FETCH_BANKDETAILS";
export const BUISNESS_STATUS = "BUISNESS_STATUS";
export const FETCH_AGREEMENT = "FETCH_AGREEMENT";
export const FETCH_AGREEMENTSTATUS = "FETCH_AGREEMENTSTATUS";